name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # รูปที่ 1: สถิติพื้นฐานแบบทั่วไป
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          optimize: no

      # รูปที่ 2: ปฏิทินแบบ 1 ปีเต็ม ธีม tokyonight
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_theme: tokyonight
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          use_prebuilt_image: yes
          optimize: no
              
      # รูปที่ 3: ไอคอน Topics ที่กดดาวไว้
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          use_prebuilt_image: yes
          optimize: no
