name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: YOUR_USERNAME

          base: header, activity, community
          plugin_languages: yes
          plugin_isocalendar: yes
